[package]
name = "nv1-hub-core"
version = "0.1.0"
edition = "2021"

[dependencies]
nv1-msg = { workspace = true }
libm = { workspace = true }
num-traits = { workspace = true }
pid = { workspace = true }
rgb = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
postcard = { workspace = true }
