[workspace]
resolver = "3"
members = [
	"nv1-hub-stm32",
	"nv1-hub-ui",
	"nv1-hub-ui-tester",
	"nv1-md",
]

[workspace.dependencies]

[profile.dev]
debug = true
lto = true
opt-level = "s"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = "s"
incremental = true
