[workspace]
resolver = "2"
members = ["nv1-ros-communicator", "nv1-ros-onnx", "nv1-ros-opencv"]

[workspace.dependencies]
r2r = "0.9.4"
tokio = { version = "1.39.3", features = ["full"] }
futures = "0.3.30"
clap = { version = "4.5.29", features = ["derive"] }
