cargo-features = ["per-package-target"]

[package]
edition = "2021"
name = "nv1-md"
version = "0.1.0"
forced-target = "thumbv7em-none-eabi"

[dependencies]
nv1-msg = { workspace = true }
nv1-md-core = { workspace = true }

corncobs = { workspace = true }
cortex-m = { workspace = true }
cortex-m-rt = { workspace = true }
defmt = { workspace = true, optional = true }
defmt-rtt = { workspace = true, optional = true }
embassy-executor = { workspace = true }
embassy-futures = { workspace = true }
embassy-stm32 = { workspace = true, features = ["time"] }
embassy-sync = { workspace = true }
embassy-time = { workspace = true }
embedded-alloc = { workspace = true }
heapless = { workspace = true }
libm = { workspace = true }
midly = { workspace = true }
panic-halt = { workspace = true }
panic-probe = { workspace = true, optional = true }
pid = { workspace = true }
postcard = { workspace = true }

[[bin]]
name = "nv1-md"
test = false
bench = false

[features]
defmt = ["dep:defmt"]
defmt-rtt = ["dep:defmt-rtt"]
panic-probe = ["dep:panic-probe"]
default = ["debug"]
debug = [
    "defmt",
    "defmt-rtt",
    "panic-probe",
    "embassy-executor/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "embassy-time/defmt",
    "embassy-time/defmt-timestamp-uptime",
    "embassy-stm32/defmt",
]
