[target.thumbv7em-none-eabi]
runner = 'probe-rs run --chip STM32F446RETx --connect-under-reset'

[build]
target = "thumbv7em-none-eabi"

[env]
DEFMT_LOG = "trace"
CMAKE_POLICY_VERSION_MINIMUM = "3.5"
