[workspace]
resolver = "3"
members = [
    "nv1-md",
    "nv1-md-core",
    "nv1-hub",
    "nv1-hub-core",
    "nv1-hub-ui",
    "nv1-hub-ui-tester",
]

[profile.dev]
debug = true
lto = true
opt-level = "s"
incremental = true

[profile.release]
debug = false
lto = true
opt-level = "s"
incremental = true

[profile.dev.package.nv1-md]
opt-level = 3

[profile.release.package.nv1-md]
opt-level = 3
